/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-04 10:52:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1572595972805L));
    _jspx_dependants.put("jar:file:/C:/Users/KimHyunWoo/Documents/evening/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<script src=\"resources/js/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/icomoon.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Flexslider  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/flexslider.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Date Picker -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<!-- Flaticons  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Gothic+A1|Noto+Sans+KR&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Mypage style (경희) -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/mypage.css\">\r\n");
      out.write("<!-- Modernizr JS -->\r\n");
      out.write("<script src=\"resources/js/modernizr-2.6.2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\t/* font-family: 'Gothic A1', sans-serif; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover, a:active, a:focus {\r\n");
      out.write("\tcolor: #D98396;\r\n");
      out.write("\toutline: none;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ebFooter {\r\n");
      out.write("\tbottom: 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ebHeader {\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ebHeader-bar {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("\t/* overflow: hidden; */\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("\tborder-bottom: .5px solid whitesmoke;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll .ebHeader-bar {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll2 .ebHeader-bar {\r\n");
      out.write("\theight: 0px;\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scroll #hLogo {\r\n");
      out.write("\theight: 38px;\r\n");
      out.write("\twidth: 38px;\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("\tmargin: 1px 0 0 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hNav {\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hNav a {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hNav>li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tmin-width: 60px;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\t/* cursor: pointer; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navTag {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hLogo {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 70px;\r\n");
      out.write("\theight: 70px;\r\n");
      out.write("\tbackground: gray;\r\n");
      out.write("\tmargin: 4px 0 0 4px;\r\n");
      out.write("\ttransition: .1s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hLogo img {\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog {\r\n");
      out.write("\tz-index: 99;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tposition: relative; /* \r\n");
      out.write("\tborder-bottom: 1px solid #D98396; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog ul {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog div {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder-bottom: whitesmoke;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog-tap {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\t/* border: .1px solid black; */\r\n");
      out.write("\tmargin: 15px 2px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog-tap>ul li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin: 4px 0 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalogTag {\r\n");
      out.write("\tz-index: 10;\r\n");
      out.write("\tmargin-top: -5px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 0px;\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("\tbackground: #F2D7C6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog-tap:hover {\r\n");
      out.write("\tbackground: #F2D7C6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".catalog-tap.on .catalogTag {\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("\t/* border: .1px solid black; */\r\n");
      out.write("\tborder-top: 5px;\r\n");
      out.write("\theight: 135px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 980px) {\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_sub {\r\n");
      out.write("\t/* position: relative; */\r\n");
      out.write("\tz-index: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_sub>div {\r\n");
      out.write("\theight: 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\twidth: 75px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_sub.on {\r\n");
      out.write("\ttransition: .5s;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tborder-top-right-radius: 5px;\r\n");
      out.write("\tborder-top-left-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_sub.on>div {\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#test {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#test a {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("span:after, span:before {\r\n");
      out.write("\tbackground: #D98396 !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 메뉴바는 어느 페이지든 포함하고 있을 테니 여기서 contextPath 변수 값 만들어주자 -->\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<header class=\"ebHeader\">\r\n");
      out.write("\t\t<div class=\"ebHeader-bar no-drag\">\r\n");
      out.write("\t\t\t<div style=\"height: 100%; overflow: hidden;\">\r\n");
      out.write("\t\t\t\t<div id=\"hLogo\">\r\n");
      out.write("\t\t\t\t\t<img src=\"resources/images/eve-logo.png\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"navTag\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"hNav\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">경매</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">중고거래</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- 비회원시 -->\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- 로그인시 -->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav_sub\"><a>마이페이지</a>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"position: fixed;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul id=\"test\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"myinfo.me\">내정보보기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"favorites.me\">관심 목록</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"dealDetail.me\">거래 내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a href=\"mypost.me\">내가 쓴 글</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t<li><img src=\"../push_bell/img/bell.png\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"catalog no-drag\">\r\n");
      out.write("\t\t<div style=\"text-align: center; display: inline-block;\">\r\n");
      out.write("\t\t\t<ul class=\"catalog-ul\">\r\n");
      out.write("\t\t\t\t<li class=\"catalog-tap\"><a style=\"font-size: 21px;\">중고</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"catalogTag\">\r\n");
      out.write("\t\t\t\t\t\t<li>중고</li>\r\n");
      out.write("\t\t\t\t\t\t<li>중고</li>\r\n");
      out.write("\t\t\t\t\t\t<li>중고</li>\r\n");
      out.write("\t\t\t\t\t\t<li>중고</li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"catalog-tap\" onclick=\"location.href='auctionList.bo'\"><a style=\"font-size: 21px;\">경매</a>\r\n");
      out.write("\t\t\t\t\t<!-- <ul class=\"catalogTag\">\r\n");
      out.write("\t\t\t\t\t\t<li>경매</li>\r\n");
      out.write("\t\t\t\t\t\t<li>경매</li>\r\n");
      out.write("\t\t\t\t\t\t<li>경매</li>\r\n");
      out.write("\t\t\t\t\t\t<li>경매</li>\r\n");
      out.write("\t\t\t\t\t</ul> --></li>\r\n");
      out.write("\t\t\t\t<li class=\"catalog-tap\"><a style=\"font-size: 21px;\">게시판</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"catalogTag\">\r\n");
      out.write("\t\t\t\t\t\t<li>게시판</li>\r\n");
      out.write("\t\t\t\t\t\t<li>게시판</li>\r\n");
      out.write("\t\t\t\t\t\t<li>게시판</li>\r\n");
      out.write("\t\t\t\t\t\t<li>게시판</li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"gototop js-top\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up2\"></i></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar scla = window.scrollY || document.documentElement.scrollTop;\r\n");
      out.write("\t\tvar before = scla;\r\n");
      out.write("\t\t$(document).scroll(function (e) {\r\n");
      out.write("\t\t\tscla = window.scrollY || document.documentElement.scrollTop;\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (scla > 15) {\r\n");
      out.write("\t\t\t\t$('.ebHeader').addClass('scroll');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (before < scla && scla > 50) {\r\n");
      out.write("\t\t\t\t\t$('.ebHeader').addClass('scroll2');\r\n");
      out.write("\t\t\t\t\t$('.nav_sub').removeClass('on');\r\n");
      out.write("\t\t\t\t\tconsole.log('up');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('.ebHeader').removeClass('scroll2')\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t// else {\r\n");
      out.write("\t\t\t\t//     $('.ebHeader').removeClass('scroll2');\r\n");
      out.write("\t\t\t\t//     console.log('down');\r\n");
      out.write("\t\t\t\t// }\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('.ebHeader').removeClass('scroll');\r\n");
      out.write("\t\t\t\t$('.ebHeader').removeClass('scroll2')\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tbefore = scla;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('.catalog-tap').hover(function () {\r\n");
      out.write("\t\t\t$(this).addClass('on');\r\n");
      out.write("\t\t\t$(this).siblings().removeClass('on');\r\n");
      out.write("\t\t}, function () {\r\n");
      out.write("\t\t\t$(this).removeClass('on');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('.catalog-ul li').hover(function () {\r\n");
      out.write("\t\t\t$(this).addClass('on');\r\n");
      out.write("\t\t\t$(this).siblings().removeClass('on');\r\n");
      out.write("\t\t}, function () {\r\n");
      out.write("\t\t\t$(this).removeClass('on');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('.nav_sub').hover(function () {\r\n");
      out.write("\t\t\t$(this).addClass('on');\r\n");
      out.write("\t\t\t$(this).siblings().removeClass('on');\r\n");
      out.write("\t\t}, function () {\r\n");
      out.write("\t\t\t$(this).removeClass('on');\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jQuery -->\r\n");
      out.write("\t<script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<!-- jQuery Easing -->\r\n");
      out.write("\t<script src=\"resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<!-- Bootstrap -->\r\n");
      out.write("\t<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- Waypoints -->\r\n");
      out.write("\t<script src=\"resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<!-- Flexslider -->\r\n");
      out.write("\t<script src=\"resources/js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("\t<!-- Owl carousel -->\r\n");
      out.write("\t<script src=\"resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<!-- Magnific Popup -->\r\n");
      out.write("\t<script src=\"resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/magnific-popup-options.js\"></script>\r\n");
      out.write("\t<!-- Date Picker -->\r\n");
      out.write("\t<script src=\"resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<!-- Stellar Parallax -->\r\n");
      out.write("\t<script src=\"resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<!-- Main -->\r\n");
      out.write("\t<script src=\"resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"resources/js/mypage.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(258,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/header.jsp(258,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/header.jsp(258,1) '${ pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/common/header.jsp(258,1) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(303,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("auction");
      // /WEB-INF/views/common/header.jsp(303,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("auctionList.bo");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
