/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-11-01 08:20:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1572595972805L));
    _jspx_dependants.put("jar:file:/C:/Users/KimHyunWoo/Documents/evening/finalProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>중고물품거래, 경매는 이브닝</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<div class=\"page\">\r\n");
      out.write("\t<aside id=\"colorlib-hero\">\r\n");
      out.write("\t\t\t<div class=\"flexslider\">\r\n");
      out.write("\t\t\t\t<ul class=\"slides\">\r\n");
      out.write("\t\t\t   \t<li style=\"background-image: url(resources/images/img-big.JPG);\">\r\n");
      out.write("\t\t\t   \t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t\t   \t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t   \t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t   \t\t\t<div class=\"col-md-6 col-md-offset-3 col-md-pull-2 col-sm-12 col-xs-12 slider-text\">\r\n");
      out.write("\t\t\t\t   \t\t\t\t<div class=\"slider-text-inner\">\r\n");
      out.write("\t\t\t\t   \t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<h2 class=\"head-1\">실시간 인기 상품을</h2>\r\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<h2 class=\"head-2\">아래에서</h2>\r\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<h2 class=\"head-3\">만나보세요</h2>\r\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<p class=\"category\"><span>중고거래 &amp; 중고제품 경매를 한 곳에서</span></p>\r\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<button class=\"btn btn-primary\" id=\"btn1\">인기상품 보기</button>\r\n");
      out.write("\t\t\t\t\t   \t\t\t\t\t<!-- <p><a href=\"\" id=\"btn1\" class=\"btn btn-primary\">인기상품 보기</a></p> -->\r\n");
      out.write("\t\t\t\t   \t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t   \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t   \t\t\t</div>\r\n");
      out.write("\t\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t   \t\t</div>\r\n");
      out.write("\t\t\t   \t</li>\r\n");
      out.write("\t\t\t  \t</ul>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#btn1').click(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar offset = $('#moveto').offset(); //선택한 태그의 위치를 반환\r\n");
      out.write("\r\n");
      out.write("\t                //animate()메서드를 이용해서 선택한 태그의 스크롤 위치를 지정해서 0.4초 동안 부드럽게 해당 위치로 이동함 \r\n");
      out.write("\r\n");
      out.write("\t\t        $('html').animate({scrollTop : offset.top}, 400);\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!--- 내용 입력 페이지 (실시간 품목) -->\r\n");
      out.write("\t\t<div class=\"colorlib-shop\">\r\n");
      out.write("\t\t\t<div class=\"container\"><br><br>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-md-offset-3 text-center colorlib-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h2 id=\"moveto\"><span style=\"font-size: 50px;\">실시간 인기 품목</span></h2>\r\n");
      out.write("\t\t\t\t\t\t<p>곧 마감되는 경매품목이나 사람들이 많은 관심을 가지고있는 중고제품들</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-5.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-6.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-7.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-8.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 여기까지 실시간 품목 라인-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 신규등록 품목-->\r\n");
      out.write("\t\t<div class=\"colorlib-shop\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 col-md-offset-3 text-center colorlib-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h2><span style=\"font-size: 50px;\">신규 등록된 품목</span></h2>\r\n");
      out.write("\t\t\t\t\t\t<p>올라온지 일주일도 안된 품목들</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-5.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-6.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-7.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"product-entry\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"product-img\" style=\"background-image: url(images/item-8.jpg);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"tag\"><span class=\"new\">New</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"cart\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"addtocart\"><a href=\"cart.html\"><i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"icon-shopping-cart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"product-detail.html\"><i class=\"icon-eye\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"#\"><i class=\"icon-heart3\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span><a href=\"add-to-wishlist.html\"><i class=\"icon-bar-chart\"></i></a></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"desc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3><a href=\"shop.html\">Floral Dress</a></h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"price\"><span>$300.00</span></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 신규 품목 종료-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 페이지 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /index.jsp(11,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/WEB-INF/views/common/header.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /index.jsp(261,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/WEB-INF/views/common/footer.jsp");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }
}
